---
title: "R Notebook"
output: html_notebook
---

```{r}
library(aPhotoDeDD)
library(magick)

pixels = 400
pic1 <- demo_dd("MM.jpg")
pic1 = adjustPicture(pic1,bsh=c(100,0,100),pixels=pixels,return=0)
pic1

```
```{r}
border = 1.1
withinBorder = .1  #border between pictures
center0 = pixels*border/2  #center of picture
wxh = image_info(pic1)[2:3]

canvasPixels = as.numeric(border*max(wxh[2],(2 + withinBorder)*wxh[1]))
leftBorder = (canvasPixels-(2+withinBorder)*wxh[1])/2
topBorder = 0.75*(canvasPixels - wxh[2])/2

centerBorder = canvasPixels - 2*leftBorder - 2*wxh[1]
  

canvasSize = paste0(canvasPixels,"x",canvasPixels)
canvas = image_resize(greyPaper, canvasSize)
canvas0 = image_blank(wxh[1],wxh[2],col="grey55")
canvasF = image_blank(canvasPixels,canvasPixels,col="grey55")

picDark = image_composite(canvas0,pic1,operator = "darken")
picLight = image_composite(canvas0,pic1,operator = "lighten")

offSet1 = paste("+",leftBorder, "+", topBorder)
bigPicDark = image_composite(canvasF,picDark,operator="atop",offset = offSet1)

bigPicLight = image_flop( image_composite(canvasF,image_flop(picLight),operator="atop",offset = offSet1) )

bigPicLight2 =  image_composite(canvasF, picLight, operator="atop", offset = offSet1) 

offSet1 = paste("+",leftBorder + wxh[1] + centerBorder , "+",topBorder)

bigPicBoth = image_composite(bigPicDark,picLight,operator="atop",offset = offSet1)
 
#bigPicBoth2 = image_flop(bigPicBoth)


bigPicBoth2 = image_composite(bigPicLight2,picDark, operator="atop",offset = offSet1)

alldone = image_morph(c(canvasF,
                        bigPicDark,bigPicDark,
                        bigPicLight,bigPicLight,
                        bigPicBoth,bigPicBoth,
                        bigPicBoth2,bigPicBoth2,
                        bigPicBoth,bigPicBoth,
                        bigPicLight,bigPicLight,
                        bigPicDark,bigPicDark,
                        canvasF,canvasF),frames=20)
image_animate(alldone)

image_write_gif(alldone,"MM.gif")
```

